[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
hahatoco = "9jDRA8bpXP4h1r3DPRJYzJpWJzhCfqrWhf86gL3mN2Nj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
